Step 6 filter devices for platform (#153)
* Filter valid devices based on platform

* Fix existing test cases and auto gen rubocop todos.

* Explicitly check device types.

* Test platform device type mapping.

* Improve exception logging.

* Improve result_string and run_and_handle_portal_function function names.

* Update rubocop gem version and regenerate rubocop todos.

* Typo fix.

* Make Xcode.parse_xcodebuild_version_out public. (+1 squashed commit)
Squashed commits:
[b2be9bb] Use Apple Development and Distribution codesign identity from Xcode 13 in case of Xcode managed signing.

* Install bundler during check workflow.

* Skipp test_xcode_managed above Xcode 12.

* Revert "Make Xcode.parse_xcodebuild_version_out public. (+1 squashed commit)"

This reverts commit ce17c938afea0c6e7fc2be4bafed25af40523855.

* Upgrade to bundler 2.2.24.

Co-authored-by: Bence Zsigmond Nagy <nbzs1001@gmail.com>

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -54,6 +54,26 @@ workflows:
     - _check_xcode_archive
 
   test_xcode_managed:
+    before_run:
+    - _expose_xcode_version
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -e
+            if [[ ${XCODE_MAJOR_VERSION} -gt 12 ]]; then
+              echo "This test case requires Xcode < 13, skipping..."
+              exit 0
+            fi
+            envman add --key XCODE_MAJOR_VERSION_LOWER_THAN_13 --value "true"
+    - bitrise-run:
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_LOWER_THAN_13" "true"}}'
+        inputs:
+        - workflow_id: utility_test_xcode_managed
+        - bitrise_config_path: ./e2e/bitrise.yml
+
+  utility_test_xcode_managed:
     envs:
     - TEST_APP_URL: https://github.com/bitrise-io/sample-apps-ios-multi-target.git
     - TEST_APP_BRANCH: automatic
@@ -179,33 +199,55 @@ workflows:
 
   _check_outputs:
     steps:
-      - script:
-          title: Output test
-          inputs:
-            - content: |-
-                #!/bin/bash
-                set -e
-                echo "BITRISE_EXPORT_METHOD: $BITRISE_EXPORT_METHOD"
-                echo "BITRISE_DEVELOPER_TEAM: $BITRISE_DEVELOPER_TEAM"
-                echo "BITRISE_DEVELOPMENT_CODESIGN_IDENTITY: $BITRISE_DEVELOPMENT_CODESIGN_IDENTITY"
-                echo "BITRISE_DEVELOPMENT_PROFILE: $BITRISE_DEVELOPMENT_PROFILE"
-                echo "BITRISE_PRODUCTION_CODESIGN_IDENTITY: $BITRISE_PRODUCTION_CODESIGN_IDENTITY"
-                echo "BITRISE_PRODUCTION_PROFILE: $BITRISE_PRODUCTION_PROFILE"
-                if [ "$BITRISE_EXPORT_METHOD" != "$DISTRIBUTION_TYPE" ]; then exit 1; fi
+    - script:
+        title: Output test
+        inputs:
+          - content: |-
+              #!/bin/bash
+              set -e
+              echo "BITRISE_EXPORT_METHOD: $BITRISE_EXPORT_METHOD"
+              echo "BITRISE_DEVELOPER_TEAM: $BITRISE_DEVELOPER_TEAM"
+              echo "BITRISE_DEVELOPMENT_CODESIGN_IDENTITY: $BITRISE_DEVELOPMENT_CODESIGN_IDENTITY"
+              echo "BITRISE_DEVELOPMENT_PROFILE: $BITRISE_DEVELOPMENT_PROFILE"
+              echo "BITRISE_PRODUCTION_CODESIGN_IDENTITY: $BITRISE_PRODUCTION_CODESIGN_IDENTITY"
+              echo "BITRISE_PRODUCTION_PROFILE: $BITRISE_PRODUCTION_PROFILE"
+              if [ "$BITRISE_EXPORT_METHOD" != "$DISTRIBUTION_TYPE" ]; then exit 1; fi
 
   _check_xcode_archive:
     steps:
-      - xcode-archive:
-          title: Xcode archive
-          inputs:
-            - export_method: $DISTRIBUTION_TYPE
-            - project_path: ./_tmp/$BITRISE_PROJECT_PATH
-            - scheme: $BITRISE_SCHEME
-            - configuration: $BITRISE_CONFIGURATION
-            - output_tool: xcodebuild
-            - custom_export_options_plist_content: $EXPORT_OPTIONS
-            - team_id: $BITRISE_APPLE_TEAM_ID
-            - force_team_id: $BITRISE_APPLE_TEAM_ID
-      - deploy-to-bitrise-io:
-          inputs:
-            - notify_user_groups: none
+    - xcode-archive:
+        title: Xcode archive
+        inputs:
+          - export_method: $DISTRIBUTION_TYPE
+          - project_path: ./_tmp/$BITRISE_PROJECT_PATH
+          - scheme: $BITRISE_SCHEME
+          - configuration: $BITRISE_CONFIGURATION
+          - output_tool: xcodebuild
+          - custom_export_options_plist_content: $EXPORT_OPTIONS
+          - team_id: $BITRISE_APPLE_TEAM_ID
+          - force_team_id: $BITRISE_APPLE_TEAM_ID
+    - deploy-to-bitrise-io:
+        inputs:
+          - notify_user_groups: none
+
+  _expose_xcode_version:
+    steps:
+    - script:
+        title: Expose Xcode major version
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -e
+            if [[ ! -z "$XCODE_MAJOR_VERSION" ]]; then
+              echo "Xcode major version already exposed: $XCODE_MAJOR_VERSION"
+              exit 0
+            fi
+            version=`xcodebuild -version`
+            regex="Xcode ([0-9]*)."
+            if [[ ! $version =~ $regex ]]; then
+              echo "Failed to determine Xcode major version"
+              exit 1
+            fi
+            xcode_major_version=${BASH_REMATCH[1]}
+            echo "Xcode major version: $xcode_major_version"
+            envman add --key XCODE_MAJOR_VERSION --value $xcode_major_version
